---

- import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: run_setup|bool and openldap_enabled|bool
  tags:
    - setup-all
