---
# Tasks file for postfix

- name: Install packages
  apt:
    state: latest
    pkg:
      - redis
      - postfix
      - postfix-pgsql
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-pgsql
      - dovecot-sieve
      - dovecot-managesieved
      - rspamd
    update_cache: yes

- name: Delete default config
  file:
    state: absent
    path: /etc/postfix/sasl/
  tags: postfix

- name: Create mail user
  user:
    name: vmail
    home: /var/vmail

- name: Create mail user sieve directory
  file:
    path: /var/vmail/sieve/global
    state: directory
    owner: vmail
    group: vmail
    mode: 0770

- name: Create mail user mailbox directory
  file:
    path: /var/vmail/mailboxes
    state: directory
    owner: vmail
    group: vmail
    mode: 0770

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ matrix_mail_server_fqn }} {{ matrix_domain }}"
    state: present

- name: Set mailname
  copy:
    dest: "/etc/mailname"
    content: "{{ matrix_mail_server_fqn }}"

- name: Restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
- name: Template main.cf
  template:
    src: templates/main.j2
    dest: /etc/postfix/main.cf
  tags: postfix

- name: Copy master.cf
  copy:
    src: files/master.cf
    dest: /etc/postfix/master.cf
  tags: postfix

- name: Create directory for sql config
  file:
    path: /etc/postfix/sql
    state: directory
    mode: "0640"
  tags: postfix

- name: Template accounts.cf
  template:
    src: templates/sql/accounts.jq
    dest: /etc/postfix/sql/accounts.cf
    mode: "0640"
  tags: postfix

- name: Template aliases.cf
  template:
    src: templates/sql/aliases.jq
    dest: /etc/postfix/sql/aliases.cf
    mode: "0640"
  tags: postfix

- name: Template domains.cf
  template:
    src: templates/sql/domains.jq
    dest: /etc/postfix/sql/domains.cf
    mode: "0640"
  tags: postfix

- name: Template recipient-access.cf
  template:
    src: templates/sql/recipient-access.jq
    dest: /etc/postfix/sql/recipient-access.cf
    mode: "0640"
  tags: postfix

- name: Template sender-login-maps.cf
  template:
    src: templates/sql/sender-login-maps.jq
    dest: /etc/postfix/sql/sender-login-maps.cf
    mode: "0640"
  tags: postfix

- name: Template tls-policy.cf
  template:
    src: templates/sql/tls-policy.jq
    dest: /etc/postfix/sql/tls-policy.cf
    mode: "0640"
  tags: postfix

- name: Copy postscreen_access
  copy:
    src: files/postscreen_access
    dest: /etc/postfix/postscreen_access
  tags: postfix

- name: Copy without_ptr
  copy:
    src: files/without_ptr
    dest: /etc/postfix/without_ptr
  tags: postfix

- name: Copy submission_header_cleanup
  copy:
    src: files/submission_header_cleanup
    dest: /etc/postfix/submission_header_cleanup
  tags: postfix

- name: Create postmap
  command: postmap /etc/postfix/without_ptr
  tags: postfix

- name: Newaliases
  command: newaliases
  tags: postfix

- name: restart Postfix
  command: systemctl reload postfix
  tags: postfix

- name: Delete default config
  file:
    state: absent
    path: /etc/dovecot/
  tags: dovecot

- name: Create config directory
  file:
    path: /etc/dovecot
    state: directory
  tags: dovecot

- name: Template dovecot.conf
  template:
    src: templates/dovecot.j2
    dest: /etc/dovecot/dovecot.conf
    mode: "0644"
  tags: dovecot

- name: Template dovecot-sql.conf
  template:
    src: templates/dovecot-sql.j2
    dest: /etc/dovecot/dovecot-sql.conf
    mode: "0440"
  tags: dovecot

- name: Copy spam-global.sieve
  copy:
    src: files/spam-global.sieve
    dest: /var/vmail/sieve/global/spam-global.sieve
    owner: vmail
    group: vmail
    mode: "0644"
  tags: dovecot

- name: Copy learn-spam.sieve
  copy:
    src: files/learn-spam.sieve
    dest: /var/vmail/sieve/global/learn-spam.sieve
    owner: vmail
    group: vmail
    mode: "0644"
  tags: dovecot

- name: Copy learn-ham.sieve
  copy:
    src: files/learn-ham.sieve
    dest: /var/vmail/sieve/global/learn-ham.sieve
    owner: vmail
    group: vmail
    mode: "0644"
  tags: dovecot

- name: Template worker-controller.inc
  template:
    src: templates/worker-controller.j2
    dest: /etc/rspamd/local.d/worker-proxy.inc
  tags: rspamd

- name: Copy classifier-bayes.conf
  copy:
    src: files/classifier-bayes.conf
    dest: /etc/rspamd/local.d/classifier-bayes.conf
  tags: rspamd

- name: Copy logging.inc
  copy:
    src: files/logging.inc
    dest: /etc/rspamd/local.d/logging.inc
  tags: rspamd

- name: Copy milter_headers.conf
  copy:
    src: files/milter_headers.conf
    dest: /etc/rspamd/local.d/milter_headers.conf
  tags: rspamd

- name: Copy options.inc
  copy:
    src: files/options.inc
    dest: /etc/rspamd/local.d/options.inc
  tags: rspamd

- name: Copy worker-normal.inc
  copy:
    src: files/worker-proxy.inc
    dest: /etc/rspamd/local.d/worker-proxy.inc
  tags: rspamd

- name: Create directory for dkim
  file:
    path: /var/lib/rspamd/dkim/
    state: directory

- name: Check if a dkim key exists
  stat:
    path: /var/lib/rspamd/dkim/dkim_key.key
  register: dkim_key

- block:
  - name: Generate dkim private key
    shell: rspamadm dkim_keygen -b 2048 -s dkim_key -k /var/lib/rspamd/dkim/dkim_key.key > /var/lib/rspamd/dkim/dkim_key.txt
  - name: Get dkim public key
    command: cat /var/lib/rspamd/dkim/dkim_key.txt
    register: dkim_public
  - name: Show dkim public key
    debug:
      msg: "{{dkim_public.stdout}}"
  when: dkim_key.stat.exists == false or rspamd_recreate_dkim_key == true

- name: Chown dkim files
  file:
    path: /var/lib/rspamd/dkim/
    state: directory
    recurse: yes
    owner: _rspamd
    group: _rspamd
    mode: "0440"
  tags: rspamd

- name: Copy arc.conf
  copy:
    src: files/arc.conf
    dest: /etc/rspamd/local.d/arc.conf
    owner: _rspamd
    group: _rspamd
    mode: "0440"
  tags: rspamd

- name: Copy dkim_signing.conf
  copy:
    src: files/dkim_signing.conf
    dest: /etc/rspamd/local.d/dkim_signing.conf
    owner: _rspamd
    group: _rspamd
    mode: "0440"
  tags: rspamd

- name: Copy redis.conf
  copy:
    src: files/redis.conf
    dest: /etc/rspamd/local.d/redis.conf
    owner: _rspamd
    group: _rspamd
    mode: "0440"
  tags: redis

- name: Reload Postfix
  command: systemctl reload matrix-mail-postfix
  tags: postfix

- name: Reload Dovecot
  command: systemctl reload matrix-mail-dovecotx
  tags: dovecot

- name: Reload Rspamd
  command: systemctl matrix-mail-rspamd
  tags: rspamd
